server:
    port: 80
    max-http-header-size: 8192
    compression:
        min-response-size: 512
        enabled: true
        mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg
    tomcat:
          maxThreads: 10
          minSpareThreads: 3
          accesslog:
            directory: /home/blog/log/server_log
            pattern: combined
            enabled: true
#logging:
#    config: classpath:log4j2.xml
#    path: /home/blog/log/spring_log
#    level: DEBUG
#    file: ./springboot.log

spring:
    http:
        encoding.charset: UTF-8
        encoding.force: false
        multipart:
          max-file-size: 3MB
          max-request-size: 10MB
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: 123456
        url: jdbc:mysql://goskyer.org:3306/goskyer_blog?useUnicode=true&characterEncoding=utf8&useSSL=false
        driverClassName: com.mysql.jdbc.Driver
        schema: classpath:import.sql
        data: classpath:data.sql
        initialize: false
        sql-script-encoding: UTF-8
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 50
            minimum-idle: 5
    output:
      ansi:
        enabled: always
mybatis:
    type-aliases-package: org.goskyer.mapping.domain,org.goskyer.mapping.mapping
    type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler
    config-location: classpath:mybatis-config.xml
    mapperLocations: classpath:mapper/*.xml


jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "

